

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MetroWeb.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BDGestionIntegradaEntitiesContext : DbContext
{
    public BDGestionIntegradaEntitiesContext()
        : base("name=BDGestionIntegradaEntitiesContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tb_Orga_Area> tb_Orga_Area { get; set; }

    public virtual DbSet<tb_Orga_SistemasGestion> tb_Orga_SistemasGestion { get; set; }

    public virtual DbSet<tb_Orga_Usuarios> tb_Orga_Usuarios { get; set; }

    public virtual DbSet<tb_Plan_Origen> tb_Plan_Origen { get; set; }

    public virtual DbSet<tb_Plan_Problema> tb_Plan_Problema { get; set; }

    public virtual DbSet<tb_Plan_Problema_SistemaGestion> tb_Plan_Problema_SistemaGestion { get; set; }

    public virtual DbSet<tb_Plan_Tipo_Problema> tb_Plan_Tipo_Problema { get; set; }

    public virtual DbSet<tb_Indi_Indicador> tb_Indi_Indicador { get; set; }

    public virtual DbSet<tb_Indi_Indicador_SistemaGestion> tb_Indi_Indicador_SistemaGestion { get; set; }

    public virtual DbSet<tb_Indi_Tipo_Indicador> tb_Indi_Tipo_Indicador { get; set; }

    public virtual DbSet<tb_Orga_Estados> tb_Orga_Estados { get; set; }

    public virtual DbSet<tb_Indi_Indicador_Alimentar> tb_Indi_Indicador_Alimentar { get; set; }

}

}

