
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MetroWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Indi_Indicador_Alimentar
{

    public int id { get; set; }

    public Nullable<int> id_indicador { get; set; }

    public Nullable<decimal> numerador { get; set; }

    public Nullable<decimal> denominador { get; set; }

    public string flag_eliminado { get; set; }

    public Nullable<decimal> meta_minima { get; set; }

    public Nullable<decimal> meta_nominal { get; set; }

    public Nullable<decimal> meta_maxima { get; set; }

    public Nullable<int> anio_alimentacion { get; set; }

    public Nullable<int> mes_alimentacion { get; set; }



    public virtual tb_Indi_Indicador tb_Indi_Indicador { get; set; }

}

}
