
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MetroWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Indi_Indicador
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Indi_Indicador()
    {

        this.tb_Indi_Indicador_SistemaGestion = new HashSet<tb_Indi_Indicador_SistemaGestion>();

        this.tb_Indi_Indicador_Alimentar = new HashSet<tb_Indi_Indicador_Alimentar>();

    }


    public int id_indicador { get; set; }

    public string nombre_indicador { get; set; }

    public string abreviatura { get; set; }

    public Nullable<long> frecuencia { get; set; }

    public Nullable<int> id_estado { get; set; }

    public string publico { get; set; }

    public Nullable<int> id_area { get; set; }

    public Nullable<decimal> meta_maxima { get; set; }

    public Nullable<decimal> meta_minima { get; set; }

    public Nullable<decimal> meta_nominal { get; set; }

    public string nominador_denominador { get; set; }

    public string descripcion_numerador { get; set; }

    public string descripcion_denominador { get; set; }

    public string flag_eliminado { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<long> id_tipo_indicador { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> correlativo_int { get; set; }

    public string descripcion_valor_unico { get; set; }

    public Nullable<int> id_usuario_alimentador { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Indi_Indicador_SistemaGestion> tb_Indi_Indicador_SistemaGestion { get; set; }

    public virtual tb_Indi_Tipo_Indicador tb_Indi_Tipo_Indicador { get; set; }

    public virtual tb_Orga_Area tb_Orga_Area { get; set; }

    public virtual tb_Orga_Estados tb_Orga_Estados { get; set; }

    public virtual tb_Orga_Usuarios tb_Orga_Usuarios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Indi_Indicador_Alimentar> tb_Indi_Indicador_Alimentar { get; set; }

}

}
