
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MetroWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Indi_Indicador_SistemaGestion
{

    public long id { get; set; }

    public Nullable<int> id_sistema_gestion { get; set; }

    public Nullable<int> id_indicador { get; set; }

    public string flag_eliminado { get; set; }

    public string usuario_modificacion { get; set; }

    public string usuario_creacion { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_eliminacion { get; set; }



    public virtual tb_Indi_Indicador tb_Indi_Indicador { get; set; }

    public virtual tb_Orga_SistemasGestion tb_Orga_SistemasGestion { get; set; }

}

}
