
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MetroWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Plan_Origen
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Plan_Origen()
    {

        this.tb_Plan_Problema = new HashSet<tb_Plan_Problema>();

    }


    public int id_origen { get; set; }

    public string descripcion { get; set; }

    public string flag_eliminado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Plan_Problema> tb_Plan_Problema { get; set; }

}

}
