
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MetroWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tb_Plan_Problema
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Plan_Problema()
    {

        this.tb_Plan_Problema_SistemaGestion = new HashSet<tb_Plan_Problema_SistemaGestion>();

    }


    public int id_problema { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> id_area { get; set; }

    public Nullable<int> id_origen { get; set; }

    public Nullable<int> id_tipo_problema { get; set; }

    public Nullable<int> id_usuario_responsable { get; set; }

    public string flag_eliminado { get; set; }



    public virtual tb_Orga_Area tb_Orga_Area { get; set; }

    public virtual tb_Orga_Usuarios tb_Orga_Usuarios { get; set; }

    public virtual tb_Plan_Origen tb_Plan_Origen { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Plan_Problema_SistemaGestion> tb_Plan_Problema_SistemaGestion { get; set; }

    public virtual tb_Plan_Tipo_Problema tb_Plan_Tipo_Problema { get; set; }

}

}
